import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Maximum payload size for handling images and audio uploads (e.g. 50MB)
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));

// Lazy initializer for Google GenAI client to prevent crash on startup if key is missing
let aiClient: GoogleGenAI | null = null;
function getGenAI(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Ensure proper error payload wrapper
function formatError(error: any) {
  return {
    success: false,
    message: error.message || "An unexpected error occurred",
    details: error.stack || null,
  };
}

// API Health check
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    hasApiKey: !!process.env.GEMINI_API_KEY,
    timestamp: new Date().toISOString(),
  });
});

/**
 * 1. MULTIMODAL CHAT ASSISTANT
 */
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { message, history, systemInstruction } = req.body;
    const ai = getGenAI();

    // Reconstruct conversation with system instructions
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: [
        ...(systemInstruction ? [{ role: "user", parts: [{ text: `SYSTEM DIRECTIVE: ${systemInstruction}` }] }, { role: "model", parts: [{ text: "Directives set. I am ready." }] }] : []),
        ...(history || []),
        { role: "user", parts: [{ text: message }] }
      ],
    });

    res.json({
      success: true,
      text: response.text || "No reply generated.",
    });
  } catch (error: any) {
    console.error("Chat error:", error);
    res.status(500).json(formatError(error));
  }
});

/**
 * 2. IMAGE GENERATION
 * Supports both nano banana (gemini-2.5-flash-image / gemini-3.1-flash-image) and Imagen
 */
app.post("/api/gemini/generate-image", async (req, res) => {
  try {
    const { prompt, modelType = "nano", aspectRatio = "1:1", quality = "1K" } = req.body;
    const ai = getGenAI();

    if (modelType === "imagen") {
      // Using Imagen model
      const response = await ai.models.generateImages({
        model: "imagen-4.0-generate-001",
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: "image/jpeg",
          aspectRatio: aspectRatio as any,
        },
      });

      if (response && response.generatedImages && response.generatedImages.length > 0) {
        const base64Bytes = response.generatedImages[0].image.imageBytes;
        res.json({
          success: true,
          imageUrl: `data:image/jpeg;base64,${base64Bytes}`,
          prompt,
          model: "imagen-4.0-generate-001",
        });
      } else {
        throw new Error("No image generated by the Imagen model.");
      }
    } else {
      // Using nano banana model 'gemini-2.5-flash-image' which is developer-grade default
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio as any,
          },
        },
      });

      let base64Image = "";
      if (response.candidates && response.candidates[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            base64Image = part.inlineData.data;
            break;
          }
        }
      }

      if (base64Image) {
        res.json({
          success: true,
          imageUrl: `data:image/png;base64,${base64Image}`,
          prompt,
          model: "gemini-2.5-flash-image",
        });
      } else {
        // If the nano banana is busy or key not subscribed, try to provide a helpful fallback or friendly message
        throw new Error("Image content could not be rendered by gemini-2.5-flash-image. Ensure your API Key supports the nano banana image models or select the alternate model.");
      }
    }
  } catch (error: any) {
    console.error("Image generation error:", error);
    res.status(500).json(formatError(error));
  }
});

/**
 * 3. IMAGE PROCESSING & ANALYSIS (PHOTO LAB)
 */
app.post("/api/gemini/process-image", async (req, res) => {
  try {
    const { imageBase64, mimeType, option, customPrompt } = req.body;
    if (!imageBase64) {
      return res.status(400).json({ success: false, message: "Image content is required." });
    }

    const ai = getGenAI();

    // Prepare system instructions depending on the selected photo processing task
    let taskInstructions = "Analyze this image.";
    if (option === "ocr") {
      taskInstructions = "Выступи в роли профессионального OCR-сканера. Извлеки весь доступный текст на русском и английском языках с этого изображения с сохранением структуры. Не добавляй никаких собственных комментариев или введений, только извлеченный текст.";
    } else if (option === "describe") {
      taskInstructions = "Сделай подробное художественное и техническое описание этой фотографии. Укажи объекты, композицию, преобладающие настроения, освещение и художественный стиль.";
    } else if (option === "retouch") {
      taskInstructions = "Проанализируй качество фотографии и предложи детальные рекомендации по ее ретуши. Составь список точных текстовых промптов (для диффузионных нейросетей), которые помогут улучшить, стилизовать или изменить эту фотографию.";
    } else if (option === "palette") {
      taskInstructions = "Определи основную цветовую палитру этого изображения. Верни список из 5-6 доминирующих цветов в формате HEX-кодов со словесным описанием настроения, которое эта палитра передает.";
    } else if (option === "custom") {
      taskInstructions = customPrompt || "Проанализируй это изображение на основе запроса пользователя.";
    }

    const imagePart = {
      inlineData: {
        mimeType: mimeType || "image/jpeg",
        data: imageBase64,
      },
    };

    const textPart = {
      text: taskInstructions,
    };

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: { parts: [imagePart, textPart] },
    });

    res.json({
      success: true,
      text: response.text || "No analysis generated.",
    });
  } catch (error: any) {
    console.error("Image analysis error:", error);
    res.status(500).json(formatError(error));
  }
});

/**
 * 4. VOICE SPEECH TRANSCRIPTION AND ANALYSIS
 */
app.post("/api/gemini/process-voice", async (req, res) => {
  try {
    const { audioBase64, mimeType, actionType } = req.body;
    if (!audioBase64) {
      return res.status(400).json({ success: false, message: "Audio records are required." });
    }

    const ai = getGenAI();

    let textPrompt = "Сделай полную русскую расшифровку (транскрипцию) этого аудиосообщения.";
    if (actionType === "summary") {
      textPrompt = "Сделай подробную расшифровку этого аудиосообщения и напиши краткое содержание (summary) с выделением главных мыслей.";
    } else if (actionType === "tasks") {
      textPrompt = "Слушай внимательно это аудио. Выдели из него все практические задачи, поручения, сроки или планы. Сформулируй их в виде четкого списка задач для выполнения (to-do list со сроками и ответственными, если они упоминаются).";
    } else if (actionType === "reply") {
      textPrompt = "Прослушай аудио от руководителя или клиента. Сделай краткую расшифровку и предложи 3 отличных вежливых варианта ответа, которые можно скопировать и отправить.";
    }

    const audioPart = {
      inlineData: {
        mimeType: mimeType || "audio/webm",
        data: audioBase64,
      },
    };

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: { parts: [audioPart, { text: textPrompt }] },
    });

    res.json({
      success: true,
      text: response.text || "Не удалось распознать аудио.",
    });
  } catch (error: any) {
    console.error("Voice processing error:", error);
    res.status(500).json(formatError(error));
  }
});

/**
 * 5. WEBHOOK & MESSENGER INTEGRATION SIMULATOR
 * This endpoint simulates live automated webhooks of popular messengers (Telegram, Discord, Slack).
 */
app.post("/api/webhook/simulate", async (req, res) => {
  try {
    const { platform, apiKey, config, sender, messageText } = req.body;
    const ai = getGenAI();

    // Construct custom prompt mimicking a messenger bot configuration context
    const promptContext = `Ты — умный чат-бот, интегрированный в мессенджер ${platform}.
Конфигурация бота: "${config || 'Стандартный помощник'}".
Поступило сообщение от пользователя "${sender || 'Тестовый аккаунт'}": "${messageText}"

Напиши короткий, умный и естественный ответ на его сообщение, соблюдая особенности мессенджера (например, для Slack — деловой стиль, для Telegram — дружелюбный с эмодзи, для Discord — реактивный и веселый). Отвечай на русском языке.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptContext,
    });

    res.json({
      success: true,
      platform,
      sender: "Bot (Gemini)",
      replyText: response.text || "Привет! Я получил твое сообщение.",
      timestamp: new Date().toISOString(),
      webhookLogged: {
        receivedAt: new Date().toISOString(),
        requestHeaders: {
          "user-agent": `WebhookSimulator/${platform}`,
          "x-messenger-signature": `sha256=${Math.random().toString(16).substring(2)}`,
        },
        payloadSize: JSON.stringify(req.body).length,
      },
    });
  } catch (error: any) {
    console.error("Webhook simulator error:", error);
    res.status(500).json(formatError(error));
  }
});

// Setup development or production build pipeline
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    // Development Mode using Vite dev middleware
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
    console.log("Dev: Vite middleware loaded.");
  } else {
    // Production static asset build hosting
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
    console.log("Prod: Serving production assets from:", distPath);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`AI Assistant Server running on http://0.0.0.0:${PORT}`);
  });
}

setupServer();
